str=input("Enter a String : ")
toreplace=input("Enter String to be Replaced : ")
replacement=input("Enter Replacement String : ")
str1=str.replace(toreplace,replacement)
print("After Replacement : ",str1)
