str=input("Enter a String : ")
print("Is Upper Case : ",str.isupper())
print("Is Lower Case : ",str.islower())
print("Is Title Case : ",str.istitle())
print("Is Aplha : ",str.isalpha())
print("Lower Case : ",str.lower())
print("Upper Case : ",str.upper())
print("Length of String : ",len(str))
print("Reverse of String : "," ".join(reversed(str)))
print("Sort String : "," ".join(sorted(str)))
print("Split String : ",str.split())
print("Starts With H : ",str.startswith("H"))
print("Ends With n : ",str.endswith("n"))
