fruits=("Grapes","Apple","Orange")
colors=("Green","Red","Orange")
quantity=(20,40,60)
print("Fruits : ",fruits)
print("Colors : ",colors)
print("Quantity : ",quantity)
fc=zip(fruits,colors)
print("Fruits and Colors Zip: \n",tuple(fc))
fq=zip(fruits,quantity)
print("Fruits and Quantity Zip : \n",list(fq))
fcq=zip(fruits,colors,quantity)
print("Fruits , Colors and Quantity Zip : \n",tuple(fcq))
